# Simple set of rules for GitHub actions integration with a ROS project
#

name: Build

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: galactic
      - name: Install dependencies
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: sicks300_2
          target-ros2-distro: galactic
          skip-tests: true